const items = [
  { name: "Shirt", discount: "20-80% OFF", image: "/public/images/shirt.jpg" },
  { name: "Pants", discount: "50-60% OFF", image: "/images/shirt.jpg" },
  { name: "Shoes", discount: "10-50% OFF", image: "/images/shirt.jpg" },
  { name: "Ethnic Wear", discount: "50-80% OFF", image: "/images/shirt.jpg" },
  { name: "WFH Casual Wear", discount: "40-60% OFF", image: "/images/shirt.jpg" },
  { name: "Activeware", discount: "30-70% OFF", image: "/images/shirt.jpg" },
  { name: "Western Wear", discount: "40-80% OFF", image: "/images/shirt.jpg" },
  { name: "Sportwear", discount: "30-80% OFF", image: "/images/shirt.jpg" },
  { name: "Loungewear", discount: "30-60% OFF", image: "/images/shirt.jpg" },
  { name: "Watches", discount: "UP TO 80% OFF", image: "/images/shirt.jpg" },
  { name: "Grooming", discount: "UP TO 60% OFF", image: "/images/shirt.jpg" },
  { name: "Beauty & Makeup", discount: "UP TO 60% OFF", image: "/images/shirt.jpg" },
  { name: "Kids Wear", discount: "50-70% OFF", image: "/images/shirt.jpg" },
  { name: "Footwear", discount: "50-70% OFF", image: "/images/shirt.jpg" },
  { name: "Footwear", discount: "40-80% OFF", image: "/images/shirt.jpg" },
  { name: "Bags, Belts & Wallets", discount: "40-70% OFF", image: "/images/shirt.jpg" },
  { name: "Office Wear", discount: "40-70% OFF", image: "/images/shirt.jpg" },
  { name: "Sunglasses", discount: "30-70% OFF", image: "/images/shirt.jpg" },
  { name: "Jewellery", discount: "20-60% OFF", image: "/images/shirt.jpg" },
  { name: "Winter Wear", discount: "40-80% OFF", image: "/images/shirt.jpg" },
  { name: "Casual Jackets", discount: "30-70% OFF", image: "/images/shirt.jpg" },
  { name: "Formal Suits", discount: "50-75% OFF", image: "/images/shirt.jpg" },
  { name: "Denim Collection", discount: "40-80% OFF", image: "/images/shirt.jpg" },
  { name: "T-Shirts", discount: "30-70% OFF", image: "/images/shirt.jpg" },
  { name: "Handbags", discount: "35-65% OFF", image: "/images/shirt.jpg" },
  { name: "Travel Trolleys", discount: "40-70% OFF", image: "/images/shirt.jpg" },
  { name: "Perfumes", discount: "UP TO 50% OFF", image: "/images/shirt.jpg" },
  { name: "Hats & Caps", discount: "20-60% OFF", image: "/images/shirt.jpg" },
  { name: "Scarves & Stoles", discount: "30-70% OFF", image: "/images/shirt.jpg" },
  { name: "Swimwear", discount: "25-60% OFF", image: "/images/shirt.jpg" },
  { name: "Sleepwear", discount: "30-65% OFF", image: "/images/shirt.jpg" },
  { name: "Accessories Combo", discount: "UP TO 55% OFF", image: "/images/shirt.jpg" },
];

export default items;