const items = [
  { name: "Shirt", discount: "20-80% OFF", image: "/images/shirt.jpg", price: "499" },
  { name: "Pants", discount: "50-60% OFF", image: "/images/pants.jpg", price: "799" },
  { name: "Shoes", discount: "10-50% OFF", image: "/images/shoes.jpg", price: "1499" },
  { name: "Ethnic Wear", discount: "50-80% OFF", image: "/images/ethnic-wear.jpg", price: "1999" },
  { name: "WFH Casual Wear", discount: "40-60% OFF", image: "/images/casual-wear.jpg", price: "699" },
  { name: "Activewear", discount: "30-70% OFF", image: "/images/activewear.jpg", price: "1199" },
  { name: "Western Wear", discount: "40-80% OFF", image: "/images/western-wear.jpg", price: "999" },
  { name: "Sportswear", discount: "30-80% OFF", image: "/images/sportswear.jpg", price: "1299" },
  { name: "Loungewear", discount: "30-60% OFF", image: "/images/loungewear.jpg", price: "599" },
  { name: "Watches", discount: "UP TO 80% OFF", image: "/images/watches.jpg", price: "2499" },
  { name: "Grooming", discount: "UP TO 60% OFF", image: "/images/grooming.jpg", price: "399" },
  { name: "Beauty & Makeup", discount: "UP TO 60% OFF", image: "/images/makeup.jpg", price: "899" },
  { name: "Kids Wear", discount: "50-70% OFF", image: "/images/kids-wear.jpg", price: "459" },
  { name: "Footwear", discount: "50-70% OFF", image: "/images/footwear.jpg", price: "1399" },
  { name: "Bags, Belts & Wallets", discount: "40-70% OFF", image: "/images/accessories.jpg", price: "759" },
  { name: "Office Wear", discount: "40-70% OFF", image: "/images/office-wear.jpg", price: "1599" },
  { name: "Sunglasses", discount: "30-70% OFF", image: "/images/sunglasses.jpg", price: "999" },
  { name: "Jewellery", discount: "20-60% OFF", image: "/images/jewellery.jpg", price: "2999" },
  { name: "Winter Wear", discount: "40-80% OFF", image: "/images/winter-wear.jpg", price: "1799" },
  { name: "Casual Jackets", discount: "30-70% OFF", image: "/images/jackets.jpg", price: "2199" },
  { name: "Formal Suits", discount: "50-75% OFF", image: "/images/suits.jpg", price: "4999" },
  { name: "Denim Collection", discount: "40-80% OFF", image: "/images/denim.jpg", price: "1399" },
  { name: "T-Shirts", discount: "30-70% OFF", image: "/images/t-shirts.jpg", price: "399" },
  { name: "Handbags", discount: "35-65% OFF", image: "/images/handbags.jpg", price: "1199" },
  { name: "Travel Trolleys", discount: "40-70% OFF", image: "/images/trolleys.jpg", price: "3499" },
  { name: "Perfumes", discount: "UP TO 50% OFF", image: "/images/perfumes.jpg", price: "1899" },
  { name: "Hats & Caps", discount: "20-60% OFF", image: "/images/caps.jpg", price: "299" },
  { name: "Scarves & Stoles", discount: "30-70% OFF", image: "/images/scarves.jpg", price: "499" },
  { name: "Swimwear", discount: "25-60% OFF", image: "/images/swimwear.jpg", price: "899" },
  { name: "Sleepwear", discount: "30-65% OFF", image: "/images/sleepwear.jpg", price: "699" },
  { name: "Accessories Combo", discount: "UP TO 55% OFF", image: "/images/combo.jpg", price: "999" }
];

export default items;